powerconsum<-read.table('household_power_consumption.txt',sep=';',skip=66637,nrow=2880)
names(powerconsum)=c('Date','Time','Global_active_power','Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3')
powerconsum$Date<-as.Date(powerconsum$Date, "%d/%m/%Y")

png(filename = "plot3.png",width = 480, height = 480)
l_min<-c(min(powerconsum$Sub_metering_1),min(powerconsum$Sub_metering_2),min(powerconsum$Sub_metering_3))
l_max<-c(max(powerconsum$Sub_metering_1),max(powerconsum$Sub_metering_2),max(powerconsum$Sub_metering_3))
plot(powerconsum$Global_active_power, type="n", ylim=range(l_min,l_max), axes=F, ann=T, xlab='',ylab='Global Active Power (Kilowatts)')
axis(1, at=c(0,nrow(powerconsum)/2,nrow(powerconsum)),labels=c('Thu','Fri','Sat'))
axis(2)
box()
lines(powerconsum$Sub_metering_1)
lines(powerconsum$Sub_metering_2,col='Red')
lines(powerconsum$Sub_metering_3,col='Blue')
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),col=c('Black','Red','Blue'),lty=c(1,1,1))
dev.off()