powerconsum<-read.table('household_power_consumption.txt',sep=';',skip=66637,nrow=2880)
names(powerconsum)=c('Date','Time','Global_active_power','Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3')
powerconsum$Date<-as.Date(powerconsum$Date, "%d/%m/%Y")

png(filename = "plot2.png",width = 480, height = 480)
plot(powerconsum$Global_active_power, type="l", ylim=range(powerconsum$Global_active_power), axes=F, ann=T, xlab=NA,ylab='Global Active Power (Kilowatts)')
axis(1, at=c(0,nrow(powerconsum)/2,nrow(powerconsum)),labels=c('Thu','Fri','Sat'))
axis(2)
box()
dev.off()
